typography_spectrum: 0.6240214344579726
color:
  brandStrength: 0.1314144532661885
  lightness: 0.47038767277263105
  saturation: 0.03606316237710416
  rhythmicContrast: 0.22845214372500777
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.9594363097567111
name: Tooth & Nail
navigation:
  - name: VSCO
    url: vsco.co/brdst/
    type: external
title: Marketing Portfolio
description: A Briefcase and A Bag of Tricks
